-- Garfada - bootstrap de banco (schema + constraints + indices + seeds)
-- Escopo desta etapa: somente camada de dados em PostgreSQL.
-- Backend/API e integracao com frontend permanecem fora de escopo.

BEGIN;

-- Permite reexecutar do zero durante desenvolvimento local.
DROP VIEW IF EXISTS v_user_stats;
DROP VIEW IF EXISTS v_restaurant_stats;

DROP TABLE IF EXISTS feed_events;
DROP TABLE IF EXISTS user_follows;
DROP TABLE IF EXISTS visited_restaurants;
DROP TABLE IF EXISTS wishlist_items;
DROP TABLE IF EXISTS reviews;
DROP TABLE IF EXISTS restaurant_menu_items;
DROP TABLE IF EXISTS restaurant_photos;
DROP TABLE IF EXISTS restaurants;
DROP TABLE IF EXISTS user_favorite_cuisines;
DROP TABLE IF EXISTS cuisines;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  username TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  avatar_url TEXT,
  bio TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT users_name_not_blank_chk CHECK (BTRIM(name) <> ''),
  CONSTRAINT users_email_not_blank_chk CHECK (BTRIM(email) <> ''),
  CONSTRAINT users_username_not_blank_chk CHECK (BTRIM(username) <> '')
);

CREATE UNIQUE INDEX ux_users_email_ci ON users (LOWER(email));
CREATE UNIQUE INDEX ux_users_username_ci ON users (LOWER(username));

CREATE TABLE cuisines (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  CONSTRAINT cuisines_name_not_blank_chk CHECK (BTRIM(name) <> '')
);

CREATE TABLE user_favorite_cuisines (
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  cuisine_id BIGINT NOT NULL REFERENCES cuisines(id) ON DELETE CASCADE,
  PRIMARY KEY (user_id, cuisine_id)
);

CREATE TABLE restaurants (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  cuisine_id BIGINT NOT NULL REFERENCES cuisines(id) ON DELETE RESTRICT,
  price_range TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  address TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT restaurants_name_not_blank_chk CHECK (BTRIM(name) <> ''),
  CONSTRAINT restaurants_address_not_blank_chk CHECK (BTRIM(address) <> ''),
  CONSTRAINT restaurants_price_range_chk CHECK (price_range IN ('$', '$$', '$$$', '$$$$'))
);

CREATE TABLE restaurant_photos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id TEXT NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
  photo_url TEXT NOT NULL,
  sort_order INTEGER NOT NULL,
  CONSTRAINT restaurant_photos_photo_url_not_blank_chk CHECK (BTRIM(photo_url) <> ''),
  CONSTRAINT restaurant_photos_sort_order_chk CHECK (sort_order >= 1),
  CONSTRAINT restaurant_photos_restaurant_sort_unique UNIQUE (restaurant_id, sort_order)
);

CREATE TABLE restaurant_menu_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id TEXT NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
  item_name TEXT NOT NULL,
  price_label TEXT NOT NULL,
  sort_order INTEGER NOT NULL,
  CONSTRAINT restaurant_menu_items_item_name_not_blank_chk CHECK (BTRIM(item_name) <> ''),
  CONSTRAINT restaurant_menu_items_price_label_not_blank_chk CHECK (BTRIM(price_label) <> ''),
  CONSTRAINT restaurant_menu_items_sort_order_chk CHECK (sort_order >= 1),
  CONSTRAINT restaurant_menu_items_restaurant_sort_unique UNIQUE (restaurant_id, sort_order)
);

CREATE TABLE reviews (
  id TEXT PRIMARY KEY,
  restaurant_id TEXT NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  rating NUMERIC(2,1) NOT NULL,
  comment TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT reviews_rating_chk CHECK (rating >= 1 AND rating <= 5),
  CONSTRAINT reviews_user_restaurant_unique UNIQUE (user_id, restaurant_id)
);

CREATE TABLE wishlist_items (
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  restaurant_id TEXT NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
  added_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (user_id, restaurant_id)
);

CREATE TABLE visited_restaurants (
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  restaurant_id TEXT NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
  visited_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  user_rating NUMERIC(2,1),
  PRIMARY KEY (user_id, restaurant_id),
  CONSTRAINT visited_restaurants_user_rating_chk CHECK (
    user_rating IS NULL OR (user_rating >= 1 AND user_rating <= 5)
  )
);

CREATE TABLE user_follows (
  follower_user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  followed_user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (follower_user_id, followed_user_id),
  CONSTRAINT user_follows_no_self_follow_chk CHECK (follower_user_id <> followed_user_id)
);

CREATE TABLE feed_events (
  id TEXT PRIMARY KEY,
  type TEXT NOT NULL,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  target_user_id TEXT REFERENCES users(id) ON DELETE CASCADE,
  restaurant_id TEXT REFERENCES restaurants(id) ON DELETE CASCADE,
  review_id TEXT REFERENCES reviews(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT feed_events_type_chk CHECK (type IN ('review', 'visited', 'wishlist', 'follow')),
  CONSTRAINT feed_events_no_self_target_chk CHECK (target_user_id IS NULL OR target_user_id <> user_id),
  CONSTRAINT feed_events_payload_chk CHECK (
    (type = 'review' AND restaurant_id IS NOT NULL AND review_id IS NOT NULL AND target_user_id IS NULL) OR
    (type = 'visited' AND restaurant_id IS NOT NULL AND review_id IS NULL AND target_user_id IS NULL) OR
    (type = 'wishlist' AND restaurant_id IS NOT NULL AND review_id IS NULL AND target_user_id IS NULL) OR
    (type = 'follow' AND target_user_id IS NOT NULL AND restaurant_id IS NULL AND review_id IS NULL)
  )
);

COMMIT;
