-- Garfada - bootstrap de banco (schema + constraints + indices + seeds)
-- Escopo desta etapa: somente camada de dados em PostgreSQL.
-- Backend/API e integracao com frontend permanecem fora de escopo.

BEGIN;

-- Permite reexecutar do zero durante desenvolvimento local.
DROP VIEW IF EXISTS v_user_stats;
DROP VIEW IF EXISTS v_restaurant_stats;

DROP TABLE IF EXISTS feed_events;
DROP TABLE IF EXISTS user_follows;
DROP TABLE IF EXISTS visited_restaurants;
DROP TABLE IF EXISTS wishlist_items;
DROP TABLE IF EXISTS reviews;
DROP TABLE IF EXISTS restaurant_menu_items;
DROP TABLE IF EXISTS restaurant_photos;
DROP TABLE IF EXISTS restaurants;
DROP TABLE IF EXISTS user_favorite_cuisines;
DROP TABLE IF EXISTS cuisines;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  username TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  avatar_url TEXT,
  bio TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT users_name_not_blank_chk CHECK (BTRIM(name) <> ''),
  CONSTRAINT users_email_not_blank_chk CHECK (BTRIM(email) <> ''),
  CONSTRAINT users_username_not_blank_chk CHECK (BTRIM(username) <> '')
);

CREATE UNIQUE INDEX ux_users_email_ci ON users (LOWER(email));
CREATE UNIQUE INDEX ux_users_username_ci ON users (LOWER(username));

CREATE TABLE cuisines (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  CONSTRAINT cuisines_name_not_blank_chk CHECK (BTRIM(name) <> '')
);

CREATE TABLE user_favorite_cuisines (
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  cuisine_id BIGINT NOT NULL REFERENCES cuisines(id) ON DELETE CASCADE,
  PRIMARY KEY (user_id, cuisine_id)
);

CREATE TABLE restaurants (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  cuisine_id BIGINT NOT NULL REFERENCES cuisines(id) ON DELETE RESTRICT,
  price_range TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  address TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT restaurants_name_not_blank_chk CHECK (BTRIM(name) <> ''),
  CONSTRAINT restaurants_address_not_blank_chk CHECK (BTRIM(address) <> ''),
  CONSTRAINT restaurants_price_range_chk CHECK (price_range IN ('$', '$$', '$$$', '$$$$'))
);

CREATE TABLE restaurant_photos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id TEXT NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
  photo_url TEXT NOT NULL,
  sort_order INTEGER NOT NULL,
  CONSTRAINT restaurant_photos_photo_url_not_blank_chk CHECK (BTRIM(photo_url) <> ''),
  CONSTRAINT restaurant_photos_sort_order_chk CHECK (sort_order >= 1),
  CONSTRAINT restaurant_photos_restaurant_sort_unique UNIQUE (restaurant_id, sort_order)
);

CREATE TABLE restaurant_menu_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id TEXT NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
  item_name TEXT NOT NULL,
  price_label TEXT NOT NULL,
  sort_order INTEGER NOT NULL,
  CONSTRAINT restaurant_menu_items_item_name_not_blank_chk CHECK (BTRIM(item_name) <> ''),
  CONSTRAINT restaurant_menu_items_price_label_not_blank_chk CHECK (BTRIM(price_label) <> ''),
  CONSTRAINT restaurant_menu_items_sort_order_chk CHECK (sort_order >= 1),
  CONSTRAINT restaurant_menu_items_restaurant_sort_unique UNIQUE (restaurant_id, sort_order)
);

CREATE TABLE reviews (
  id TEXT PRIMARY KEY,
  restaurant_id TEXT NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  rating NUMERIC(2,1) NOT NULL,
  comment TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT reviews_rating_chk CHECK (rating >= 1 AND rating <= 5),
  CONSTRAINT reviews_user_restaurant_unique UNIQUE (user_id, restaurant_id)
);

CREATE TABLE wishlist_items (
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  restaurant_id TEXT NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
  added_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (user_id, restaurant_id)
);

CREATE TABLE visited_restaurants (
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  restaurant_id TEXT NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
  visited_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  user_rating NUMERIC(2,1),
  PRIMARY KEY (user_id, restaurant_id),
  CONSTRAINT visited_restaurants_user_rating_chk CHECK (
    user_rating IS NULL OR (user_rating >= 1 AND user_rating <= 5)
  )
);

CREATE TABLE user_follows (
  follower_user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  followed_user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (follower_user_id, followed_user_id),
  CONSTRAINT user_follows_no_self_follow_chk CHECK (follower_user_id <> followed_user_id)
);

CREATE TABLE feed_events (
  id TEXT PRIMARY KEY,
  type TEXT NOT NULL,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  target_user_id TEXT REFERENCES users(id) ON DELETE CASCADE,
  restaurant_id TEXT REFERENCES restaurants(id) ON DELETE CASCADE,
  review_id TEXT REFERENCES reviews(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT feed_events_type_chk CHECK (type IN ('review', 'visited', 'wishlist', 'follow')),
  CONSTRAINT feed_events_no_self_target_chk CHECK (target_user_id IS NULL OR target_user_id <> user_id),
  CONSTRAINT feed_events_payload_chk CHECK (
    (type = 'review' AND restaurant_id IS NOT NULL AND review_id IS NOT NULL AND target_user_id IS NULL) OR
    (type = 'visited' AND restaurant_id IS NOT NULL AND review_id IS NULL AND target_user_id IS NULL) OR
    (type = 'wishlist' AND restaurant_id IS NOT NULL AND review_id IS NULL AND target_user_id IS NULL) OR
    (type = 'follow' AND target_user_id IS NOT NULL AND restaurant_id IS NULL AND review_id IS NULL)
  )
);

-- Indices para filtros/joins frequentes em catalogo, perfil e feed.
CREATE INDEX idx_user_favorite_cuisines_cuisine_id
  ON user_favorite_cuisines (cuisine_id);

CREATE INDEX idx_restaurants_cuisine_id
  ON restaurants (cuisine_id);

CREATE INDEX idx_restaurants_price_range
  ON restaurants (price_range);

CREATE INDEX idx_restaurants_name_lower
  ON restaurants (LOWER(name));

CREATE INDEX idx_restaurants_address_lower
  ON restaurants (LOWER(address));

CREATE INDEX idx_restaurant_photos_restaurant_sort
  ON restaurant_photos (restaurant_id, sort_order);

CREATE INDEX idx_restaurant_menu_items_restaurant_sort
  ON restaurant_menu_items (restaurant_id, sort_order);

CREATE INDEX idx_reviews_restaurant_created_at
  ON reviews (restaurant_id, created_at DESC);

CREATE INDEX idx_reviews_user_created_at
  ON reviews (user_id, created_at DESC);

CREATE INDEX idx_wishlist_items_user_added_at
  ON wishlist_items (user_id, added_at DESC);

CREATE INDEX idx_wishlist_items_restaurant_id
  ON wishlist_items (restaurant_id);

CREATE INDEX idx_visited_restaurants_user_visited_at
  ON visited_restaurants (user_id, visited_at DESC);

CREATE INDEX idx_visited_restaurants_restaurant_id
  ON visited_restaurants (restaurant_id);

CREATE INDEX idx_user_follows_followed_user_id
  ON user_follows (followed_user_id);

CREATE INDEX idx_feed_events_created_at_desc
  ON feed_events (created_at DESC);

CREATE INDEX idx_feed_events_user_created_at
  ON feed_events (user_id, created_at DESC);

CREATE INDEX idx_feed_events_target_user_created_at
  ON feed_events (target_user_id, created_at DESC);

CREATE INDEX idx_feed_events_restaurant_created_at
  ON feed_events (restaurant_id, created_at DESC);

CREATE VIEW v_restaurant_stats AS
SELECT
  r.id AS restaurant_id,
  COALESCE(ROUND(AVG(rv.rating)::NUMERIC, 1), 0.0) AS average_rating,
  COUNT(rv.id) AS reviews_count,
  COUNT(NULLIF(BTRIM(rv.comment), '')) AS comments_count,
  COALESCE(vs.visits_count, 0) AS visits_count
FROM restaurants r
LEFT JOIN reviews rv ON rv.restaurant_id = r.id
LEFT JOIN (
  SELECT
    restaurant_id,
    COUNT(*) AS visits_count
  FROM visited_restaurants
  GROUP BY restaurant_id
) vs ON vs.restaurant_id = r.id
GROUP BY r.id, vs.visits_count;

CREATE VIEW v_user_stats AS
SELECT
  u.id AS user_id,
  COALESCE(rv.reviews_count, 0) AS reviews_count,
  COALESCE(vt.visited_count, 0) AS visited_count,
  COALESCE(ws.wishlist_count, 0) AS wishlist_count,
  COALESCE(fr.followers_count, 0) AS followers_count,
  COALESCE(fg.following_count, 0) AS following_count
FROM users u
LEFT JOIN (
  SELECT user_id, COUNT(*) AS reviews_count
  FROM reviews
  GROUP BY user_id
) rv ON rv.user_id = u.id
LEFT JOIN (
  SELECT user_id, COUNT(*) AS visited_count
  FROM visited_restaurants
  GROUP BY user_id
) vt ON vt.user_id = u.id
LEFT JOIN (
  SELECT user_id, COUNT(*) AS wishlist_count
  FROM wishlist_items
  GROUP BY user_id
) ws ON ws.user_id = u.id
LEFT JOIN (
  SELECT followed_user_id AS user_id, COUNT(*) AS followers_count
  FROM user_follows
  GROUP BY followed_user_id
) fr ON fr.user_id = u.id
LEFT JOIN (
  SELECT follower_user_id AS user_id, COUNT(*) AS following_count
  FROM user_follows
  GROUP BY follower_user_id
) fg ON fg.user_id = u.id;

COMMIT;
