-- Garfada - bootstrap de banco (schema + constraints + indices + seeds)
-- Escopo desta etapa: somente camada de dados em PostgreSQL.
-- Backend/API e integracao com frontend permanecem fora de escopo.

BEGIN;

-- Permite reexecutar do zero durante desenvolvimento local.
DROP VIEW IF EXISTS v_user_stats;
DROP VIEW IF EXISTS v_restaurant_stats;

DROP TABLE IF EXISTS feed_events;
DROP TABLE IF EXISTS user_follows;
DROP TABLE IF EXISTS visited_restaurants;
DROP TABLE IF EXISTS wishlist_items;
DROP TABLE IF EXISTS reviews;
DROP TABLE IF EXISTS restaurant_menu_items;
DROP TABLE IF EXISTS restaurant_photos;
DROP TABLE IF EXISTS restaurants;
DROP TABLE IF EXISTS user_favorite_cuisines;
DROP TABLE IF EXISTS cuisines;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  username TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  avatar_url TEXT,
  bio TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT users_name_not_blank_chk CHECK (BTRIM(name) <> ''),
  CONSTRAINT users_email_not_blank_chk CHECK (BTRIM(email) <> ''),
  CONSTRAINT users_username_not_blank_chk CHECK (BTRIM(username) <> '')
);

CREATE UNIQUE INDEX ux_users_email_ci ON users (LOWER(email));
CREATE UNIQUE INDEX ux_users_username_ci ON users (LOWER(username));

CREATE TABLE cuisines (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  CONSTRAINT cuisines_name_not_blank_chk CHECK (BTRIM(name) <> '')
);

CREATE TABLE user_favorite_cuisines (
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  cuisine_id BIGINT NOT NULL REFERENCES cuisines(id) ON DELETE CASCADE,
  PRIMARY KEY (user_id, cuisine_id)
);

CREATE TABLE restaurants (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  cuisine_id BIGINT NOT NULL REFERENCES cuisines(id) ON DELETE RESTRICT,
  price_range TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  address TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT restaurants_name_not_blank_chk CHECK (BTRIM(name) <> ''),
  CONSTRAINT restaurants_address_not_blank_chk CHECK (BTRIM(address) <> ''),
  CONSTRAINT restaurants_price_range_chk CHECK (price_range IN ('$', '$$', '$$$', '$$$$'))
);

CREATE TABLE restaurant_photos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id TEXT NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
  photo_url TEXT NOT NULL,
  sort_order INTEGER NOT NULL,
  CONSTRAINT restaurant_photos_photo_url_not_blank_chk CHECK (BTRIM(photo_url) <> ''),
  CONSTRAINT restaurant_photos_sort_order_chk CHECK (sort_order >= 1),
  CONSTRAINT restaurant_photos_restaurant_sort_unique UNIQUE (restaurant_id, sort_order)
);

CREATE TABLE restaurant_menu_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id TEXT NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
  item_name TEXT NOT NULL,
  price_label TEXT NOT NULL,
  sort_order INTEGER NOT NULL,
  CONSTRAINT restaurant_menu_items_item_name_not_blank_chk CHECK (BTRIM(item_name) <> ''),
  CONSTRAINT restaurant_menu_items_price_label_not_blank_chk CHECK (BTRIM(price_label) <> ''),
  CONSTRAINT restaurant_menu_items_sort_order_chk CHECK (sort_order >= 1),
  CONSTRAINT restaurant_menu_items_restaurant_sort_unique UNIQUE (restaurant_id, sort_order)
);

CREATE TABLE reviews (
  id TEXT PRIMARY KEY,
  restaurant_id TEXT NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  rating NUMERIC(2,1) NOT NULL,
  comment TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT reviews_rating_chk CHECK (rating >= 1 AND rating <= 5),
  CONSTRAINT reviews_user_restaurant_unique UNIQUE (user_id, restaurant_id)
);

CREATE TABLE wishlist_items (
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  restaurant_id TEXT NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
  added_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (user_id, restaurant_id)
);

CREATE TABLE visited_restaurants (
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  restaurant_id TEXT NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
  visited_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  user_rating NUMERIC(2,1),
  PRIMARY KEY (user_id, restaurant_id),
  CONSTRAINT visited_restaurants_user_rating_chk CHECK (
    user_rating IS NULL OR (user_rating >= 1 AND user_rating <= 5)
  )
);

CREATE TABLE user_follows (
  follower_user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  followed_user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (follower_user_id, followed_user_id),
  CONSTRAINT user_follows_no_self_follow_chk CHECK (follower_user_id <> followed_user_id)
);

CREATE TABLE feed_events (
  id TEXT PRIMARY KEY,
  type TEXT NOT NULL,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  target_user_id TEXT REFERENCES users(id) ON DELETE CASCADE,
  restaurant_id TEXT REFERENCES restaurants(id) ON DELETE CASCADE,
  review_id TEXT REFERENCES reviews(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT feed_events_type_chk CHECK (type IN ('review', 'visited', 'wishlist', 'follow')),
  CONSTRAINT feed_events_no_self_target_chk CHECK (target_user_id IS NULL OR target_user_id <> user_id),
  CONSTRAINT feed_events_payload_chk CHECK (
    (type = 'review' AND restaurant_id IS NOT NULL AND review_id IS NOT NULL AND target_user_id IS NULL) OR
    (type = 'visited' AND restaurant_id IS NOT NULL AND review_id IS NULL AND target_user_id IS NULL) OR
    (type = 'wishlist' AND restaurant_id IS NOT NULL AND review_id IS NULL AND target_user_id IS NULL) OR
    (type = 'follow' AND target_user_id IS NOT NULL AND restaurant_id IS NULL AND review_id IS NULL)
  )
);

-- Indices para filtros/joins frequentes em catalogo, perfil e feed.
CREATE INDEX idx_user_favorite_cuisines_cuisine_id
  ON user_favorite_cuisines (cuisine_id);

CREATE INDEX idx_restaurants_cuisine_id
  ON restaurants (cuisine_id);

CREATE INDEX idx_restaurants_price_range
  ON restaurants (price_range);

CREATE INDEX idx_restaurants_name_lower
  ON restaurants (LOWER(name));

CREATE INDEX idx_restaurants_address_lower
  ON restaurants (LOWER(address));

CREATE INDEX idx_restaurant_photos_restaurant_sort
  ON restaurant_photos (restaurant_id, sort_order);

CREATE INDEX idx_restaurant_menu_items_restaurant_sort
  ON restaurant_menu_items (restaurant_id, sort_order);

CREATE INDEX idx_reviews_restaurant_created_at
  ON reviews (restaurant_id, created_at DESC);

CREATE INDEX idx_reviews_user_created_at
  ON reviews (user_id, created_at DESC);

CREATE INDEX idx_wishlist_items_user_added_at
  ON wishlist_items (user_id, added_at DESC);

CREATE INDEX idx_wishlist_items_restaurant_id
  ON wishlist_items (restaurant_id);

CREATE INDEX idx_visited_restaurants_user_visited_at
  ON visited_restaurants (user_id, visited_at DESC);

CREATE INDEX idx_visited_restaurants_restaurant_id
  ON visited_restaurants (restaurant_id);

CREATE INDEX idx_user_follows_followed_user_id
  ON user_follows (followed_user_id);

CREATE INDEX idx_feed_events_created_at_desc
  ON feed_events (created_at DESC);

CREATE INDEX idx_feed_events_user_created_at
  ON feed_events (user_id, created_at DESC);

CREATE INDEX idx_feed_events_target_user_created_at
  ON feed_events (target_user_id, created_at DESC);

CREATE INDEX idx_feed_events_restaurant_created_at
  ON feed_events (restaurant_id, created_at DESC);

CREATE VIEW v_restaurant_stats AS
SELECT
  r.id AS restaurant_id,
  COALESCE(ROUND(AVG(rv.rating)::NUMERIC, 1), 0.0) AS average_rating,
  COUNT(rv.id) AS reviews_count,
  COUNT(NULLIF(BTRIM(rv.comment), '')) AS comments_count,
  COALESCE(vs.visits_count, 0) AS visits_count
FROM restaurants r
LEFT JOIN reviews rv ON rv.restaurant_id = r.id
LEFT JOIN (
  SELECT
    restaurant_id,
    COUNT(*) AS visits_count
  FROM visited_restaurants
  GROUP BY restaurant_id
) vs ON vs.restaurant_id = r.id
GROUP BY r.id, vs.visits_count;

CREATE VIEW v_user_stats AS
SELECT
  u.id AS user_id,
  COALESCE(rv.reviews_count, 0) AS reviews_count,
  COALESCE(vt.visited_count, 0) AS visited_count,
  COALESCE(ws.wishlist_count, 0) AS wishlist_count,
  COALESCE(fr.followers_count, 0) AS followers_count,
  COALESCE(fg.following_count, 0) AS following_count
FROM users u
LEFT JOIN (
  SELECT user_id, COUNT(*) AS reviews_count
  FROM reviews
  GROUP BY user_id
) rv ON rv.user_id = u.id
LEFT JOIN (
  SELECT user_id, COUNT(*) AS visited_count
  FROM visited_restaurants
  GROUP BY user_id
) vt ON vt.user_id = u.id
LEFT JOIN (
  SELECT user_id, COUNT(*) AS wishlist_count
  FROM wishlist_items
  GROUP BY user_id
) ws ON ws.user_id = u.id
LEFT JOIN (
  SELECT followed_user_id AS user_id, COUNT(*) AS followers_count
  FROM user_follows
  GROUP BY followed_user_id
) fr ON fr.user_id = u.id
LEFT JOIN (
  SELECT follower_user_id AS user_id, COUNT(*) AS following_count
  FROM user_follows
  GROUP BY follower_user_id
) fg ON fg.user_id = u.id;

-- Seeds iniciais alinhados aos mocks do frontend.
INSERT INTO users (id, name, email, username, password_hash, avatar_url, bio) VALUES
  ('u1', 'Pedro Salles', 'pedro@garfada.app', 'pedrins', 'pbkdf2_sha256$120000$Z2FyZmFkYS11MS1zYWx0$thLcIIagd67MglsLHuxFgjZyDd0oRVgygzqBhG206nc', 'https://i.pravatar.cc/160?img=13', 'Café forte, comida mineira e descobertas de bairro.'),
  ('u2', 'Camila Prado', 'camila@garfada.app', 'camilaprado', 'pbkdf2_sha256$120000$Z2FyZmFkYS11Mi1zYWx0$TpV3igYaOPFbQOWHRfYJ6Mxb01LKh0kVtj8HmEMFXeI', 'https://i.pravatar.cc/160?img=32', 'Amo menus degustação e sobremesas autorais.'),
  ('u3', 'João Nogueira', 'joao@garfada.app', 'joaonog', 'pbkdf2_sha256$120000$Z2FyZmFkYS11My1zYWx0$-oll5jE33roMUzLNQ2HEZ21_sobmM2-4nDLCsllkIpg', 'https://i.pravatar.cc/160?img=12', 'Roteiro de botecos, churrascos e bons hambúrgueres.'),
  ('u4', 'Lívia Azevedo', 'livia@garfada.app', 'livaz', 'pbkdf2_sha256$120000$Z2FyZmFkYS11NC1zYWx0$aVqmPtycLtDufUhxbl-pSrVe-YcrNz0RbsAAjhv3DUA', 'https://i.pravatar.cc/160?img=44', 'Vegetariana e pesquisadora de restaurantes sustentáveis.'),
  ('u5', 'Rafael Gomes', 'rafael@garfada.app', 'rafagourmet', 'pbkdf2_sha256$120000$Z2FyZmFkYS11NS1zYWx0$5IezI8UIencKvJkUXT7XbkijatGyEZ3ogdpnCwMfJN4', 'https://i.pravatar.cc/160?img=59', 'Busco pratos sazonais e cozinha técnica.');

INSERT INTO cuisines (name) VALUES
  ('Brasileira'),
  ('Japonesa'),
  ('Italiana'),
  ('Peruana'),
  ('Churrasco'),
  ('Vegetariana'),
  ('Indiana'),
  ('Francesa');

INSERT INTO user_favorite_cuisines (user_id, cuisine_id)
SELECT
  uf.user_id,
  c.id
FROM (
  VALUES
    ('u1', 'Brasileira'),
    ('u1', 'Italiana'),
    ('u1', 'Japonesa'),
    ('u2', 'Francesa'),
    ('u2', 'Peruana'),
    ('u3', 'Churrasco'),
    ('u3', 'Brasileira'),
    ('u3', 'Indiana'),
    ('u4', 'Vegetariana'),
    ('u4', 'Indiana'),
    ('u5', 'Japonesa'),
    ('u5', 'Francesa'),
    ('u5', 'Italiana')
) AS uf(user_id, cuisine_name)
JOIN cuisines c ON c.name = uf.cuisine_name;

INSERT INTO restaurants (id, name, cuisine_id, price_range, description, address)
SELECT
  r.id,
  r.name,
  c.id,
  r.price_range,
  r.description,
  r.address
FROM (
  VALUES
    ('r1', 'Casa Mineira Contemporânea', 'Brasileira', '$$', 'Clássicos mineiros com releitura moderna e ingredientes locais.', 'Rua dos Sabores, 214 - Savassi, Belo Horizonte'),
    ('r2', 'Sakura Izakaya', 'Japonesa', '$$$', 'Combinados sazonais, cozinha quente e balcão omakase.', 'Av. do Oriente, 98 - Funcionários, Belo Horizonte'),
    ('r3', 'Forno da Vila', 'Italiana', '$$', 'Massas frescas e pizzas napolitanas fermentadas naturalmente.', 'Alameda da Vila, 77 - Lourdes, Belo Horizonte'),
    ('r4', 'Maré Alta Cevicheria', 'Peruana', '$$$', 'Ceviches autorais, frutos do mar frescos e coquetelaria cítrica.', 'Rua Atlântica, 301 - Belvedere, Belo Horizonte'),
    ('r5', 'Brasa & Pimenta BBQ', 'Churrasco', '$$', 'Carnes defumadas de longa cocção e acompanhamentos brasileiros.', 'Rua da Brasa, 451 - Prado, Belo Horizonte'),
    ('r6', 'Verde Raiz Bistrô', 'Vegetariana', '$$', 'Pratos vegetais sazonais e fermentações artesanais.', 'Rua dos Ipês, 65 - Floresta, Belo Horizonte'),
    ('r7', 'Rota do Curry', 'Indiana', '$$', 'Curries regionais, forno tandoor e especiarias moídas na casa.', 'Av. das Especiarias, 142 - Santa Efigênia, Belo Horizonte'),
    ('r8', 'Boulangerie Lumière', 'Francesa', '$$$', 'Bistrô francês com brunch estendido e carta de vinhos naturais.', 'Rua Lumière, 11 - Santo Antônio, Belo Horizonte')
) AS r(id, name, cuisine_name, price_range, description, address)
JOIN cuisines c ON c.name = r.cuisine_name;

INSERT INTO restaurant_photos (restaurant_id, photo_url, sort_order) VALUES
  ('r1', 'https://images.pexels.com/photos/5865153/pexels-photo-5865153.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=900&q=80&w=1600', 1),
  ('r1', 'https://images.pexels.com/photos/10875184/pexels-photo-10875184.jpeg?cs=srgb&dl=pexels-quang-nguyen-vinh-222549-10875184.jpg&fm=jpg', 2),
  ('r1', 'https://images.pexels.com/photos/18014528/pexels-photo-18014528.jpeg?cs=srgb&dl=pexels-huy-nguy%E1%BB%85n-3896554-18014528.jpg&fm=jpg', 3),
  ('r2', 'https://images.pexels.com/photos/14076428/pexels-photo-14076428.jpeg?cs=srgb&dl=pexels-chan-walrus-9418648-14076428.jpg&fm=jpg', 1),
  ('r2', 'https://images.pexels.com/photos/12088122/pexels-photo-12088122.jpeg?cs=srgb&dl=pexels-cottonbro-12088122.jpg&fm=jpg', 2),
  ('r2', 'https://images.pexels.com/photos/20184678/pexels-photo-20184678.jpeg?cs=srgb&dl=pexels-hardeep-johar-105894-20184678.jpg&fm=jpg', 3),
  ('r3', 'https://images.pexels.com/photos/776538/pexels-photo-776538.jpeg?cs=srgb&dl=pexels-rachel-claire-776538.jpg&fm=jpg', 1),
  ('r3', 'https://images.pexels.com/photos/30119014/pexels-photo-30119014.jpeg?cs=srgb&dl=pexels-javon-swaby-1976167-30119014.jpg&fm=jpg', 2),
  ('r3', 'https://images.pexels.com/photos/3887985/pexels-photo-3887985.jpeg?cs=srgb&dl=pexels-nerfee-mirandilla-1650246-3887985.jpg&fm=jpg', 3),
  ('r4', 'https://images.pexels.com/photos/20184683/pexels-photo-20184683.jpeg?cs=srgb&dl=pexels-hardeep-johar-105894-20184683.jpg&fm=jpg', 1),
  ('r4', 'https://images.pexels.com/photos/20184670/pexels-photo-20184670.jpeg?cs=srgb&dl=pexels-hardeep-johar-105894-20184670.jpg&fm=jpg', 2),
  ('r4', 'https://images.pexels.com/photos/20184679/pexels-photo-20184679.jpeg?cs=srgb&dl=pexels-hardeep-johar-105894-20184679.jpg&fm=jpg', 3),
  ('r5', 'https://images.pexels.com/photos/30691575/pexels-photo-30691575.jpeg?cs=srgb&dl=pexels-phit-29015188-30691575.jpg&fm=jpg', 1),
  ('r5', 'https://images.pexels.com/photos/7590623/pexels-photo-7590623.jpeg?cs=srgb&dl=pexels-%D0%B5%D0%BA%D0%B0%D1%82%D0%B5%D1%80%D0%B8%D0%BD%D0%B0-%D0%B1%D0%BE%D0%BB%D0%BE%D0%B2%D1%86%D0%BE%D0%B2%D0%B0-7309328-7590623.jpg&fm=jpg', 2),
  ('r5', 'https://images.pexels.com/photos/1846416/pexels-photo-1846416.jpeg?cs=srgb&dl=pexels-skinnyms-1846416.jpg&fm=jpg', 3),
  ('r6', 'https://images.pexels.com/photos/10045883/pexels-photo-10045883.jpeg?cs=srgb&dl=pexels-rachel-claire-6126316-10045883.jpg&fm=jpg', 1),
  ('r6', 'https://images.pexels.com/photos/10187175/pexels-photo-10187175.jpeg?cs=srgb&dl=pexels-%D0%B0%D1%80%D1%82%D0%B5%D0%BC-%D0%B2%D0%B0%D0%BB%D0%B8%D0%BD%D1%81%D0%BA%D0%B8%D0%B9-10187175.jpg&fm=jpg', 2),
  ('r6', 'https://images.pexels.com/photos/34429975/pexels-photo-34429975.jpeg?cs=srgb&dl=pexels-steve-5048917-34429975.jpg&fm=jpg', 3),
  ('r7', 'https://images.pexels.com/photos/19615767/pexels-photo-19615767.jpeg?cs=srgb&dl=pexels-sagui-andrea-200115552-19615767.jpg&fm=jpg', 1),
  ('r7', 'https://images.pexels.com/photos/2174069/pexels-photo-2174069.jpeg?cs=srgb&dl=pexels-quark-studio-1159039-2174069.jpg&fm=jpg', 2),
  ('r7', 'https://images.pexels.com/photos/1123259/pexels-photo-1123259.jpeg?cs=srgb&dl=pexels-valeria-boltneva-1123259.jpg&fm=jpg', 3),
  ('r8', 'https://images.pexels.com/photos/20184678/pexels-photo-20184678.jpeg?cs=srgb&dl=pexels-hardeep-johar-105894-20184678.jpg&fm=jpg', 1),
  ('r8', 'https://images.pexels.com/photos/776538/pexels-photo-776538.jpeg?cs=srgb&dl=pexels-rachel-claire-776538.jpg&fm=jpg', 2),
  ('r8', 'https://images.pexels.com/photos/20184683/pexels-photo-20184683.jpeg?cs=srgb&dl=pexels-hardeep-johar-105894-20184683.jpg&fm=jpg', 3);

INSERT INTO restaurant_menu_items (restaurant_id, item_name, price_label, sort_order) VALUES
  ('r1', 'Frango com quiabo braseado', 'R$ 62', 1),
  ('r1', 'Tutu de feijão com crocante de couve', 'R$ 54', 2),
  ('r1', 'Pudim de doce de leite artesanal', 'R$ 26', 3),
  ('r2', 'Omakase 8 tempos', 'R$ 198', 1),
  ('r2', 'Ramen de missô picante', 'R$ 68', 2),
  ('r2', 'Mochi artesanal do dia', 'R$ 24', 3),
  ('r3', 'Tagliatelle al ragù', 'R$ 66', 1),
  ('r3', 'Pizza marguerita DOP', 'R$ 72', 2),
  ('r3', 'Tiramisù clássico', 'R$ 28', 3),
  ('r4', 'Ceviche clássico limão-siciliano', 'R$ 74', 1),
  ('r4', 'Arroz de mariscos', 'R$ 96', 2),
  ('r4', 'Suspiro de lúcuma', 'R$ 34', 3),
  ('r5', 'Brisket defumado (300g)', 'R$ 88', 1),
  ('r5', 'Costela suína glaceada', 'R$ 76', 2),
  ('r5', 'Cheesecake de goiabada', 'R$ 25', 3),
  ('r6', 'Nhoque de mandioquinha com pesto', 'R$ 58', 1),
  ('r6', 'Bowl de legumes tostados', 'R$ 52', 2),
  ('r6', 'Torta cremosa de cogumelos', 'R$ 44', 3),
  ('r7', 'Butter chicken', 'R$ 64', 1),
  ('r7', 'Palak paneer', 'R$ 58', 2),
  ('r7', 'Naan com alho e manteiga', 'R$ 22', 3),
  ('r8', 'Croque monsieur trufado', 'R$ 70', 1),
  ('r8', 'Confit de canard', 'R$ 102', 2),
  ('r8', 'Crème brûlée', 'R$ 32', 3);

INSERT INTO reviews (id, restaurant_id, user_id, rating, comment, created_at, updated_at) VALUES
  ('rev1', 'r1', 'u2', 4.8, 'Atendimento impecável e uma sobremesa memorável.', '2026-03-26T19:20:00.000Z', '2026-03-26T19:20:00.000Z'),
  ('rev2', 'r1', 'u3', 4.2, 'Pratos bem executados, porção poderia ser um pouco maior.', '2026-03-20T21:10:00.000Z', '2026-03-20T21:10:00.000Z'),
  ('rev3', 'r2', 'u5', 4.9, 'Peixes muito frescos e omakase criativo.', '2026-03-30T22:00:00.000Z', '2026-03-30T22:00:00.000Z'),
  ('rev4', 'r2', 'u1', 4.5, 'Experiência muito boa no balcão, voltaria fácil.', '2026-03-22T22:15:00.000Z', '2026-03-22T22:15:00.000Z'),
  ('rev5', 'r3', 'u1', 4.0, 'Massa fresca excelente, ambiente acolhedor.', '2026-03-12T20:40:00.000Z', '2026-03-12T20:40:00.000Z'),
  ('rev6', 'r4', 'u2', 4.6, 'Ceviche com acidez equilibrada e ótimos drinks.', '2026-04-02T21:30:00.000Z', '2026-04-02T21:30:00.000Z'),
  ('rev7', 'r5', 'u3', 4.4, 'Carne no ponto e acompanhamentos muito bons.', '2026-03-27T23:00:00.000Z', '2026-03-27T23:00:00.000Z'),
  ('rev8', 'r6', 'u4', 4.7, 'Menu sazonal surpreendente e criativo.', '2026-03-25T19:55:00.000Z', '2026-03-25T19:55:00.000Z'),
  ('rev9', 'r6', 'u1', 4.3, 'Excelente opção vegetariana para almoço.', '2026-03-08T18:10:00.000Z', '2026-03-08T18:10:00.000Z'),
  ('rev10', 'r7', 'u4', 4.5, 'Especiarias equilibradas, naan incrível.', '2026-04-01T20:05:00.000Z', '2026-04-01T20:05:00.000Z'),
  ('rev11', 'r8', 'u5', 4.8, 'Brunch excelente e confeitaria impecável.', '2026-03-31T15:30:00.000Z', '2026-03-31T15:30:00.000Z'),
  ('rev12', 'r8', 'u2', 4.4, 'Ambiente charmoso, ótimo para encontros.', '2026-03-18T14:00:00.000Z', '2026-03-18T14:00:00.000Z');

INSERT INTO wishlist_items (user_id, restaurant_id, added_at) VALUES
  ('u1', 'r4', '2026-03-29T11:00:00.000Z'),
  ('u1', 'r8', '2026-04-03T09:20:00.000Z'),
  ('u1', 'r7', '2026-03-15T17:45:00.000Z'),
  ('u2', 'r1', '2026-03-11T10:00:00.000Z'),
  ('u3', 'r2', '2026-03-21T12:30:00.000Z'),
  ('u4', 'r5', '2026-03-26T16:40:00.000Z'),
  ('u5', 'r3', '2026-03-17T08:10:00.000Z');

INSERT INTO visited_restaurants (user_id, restaurant_id, visited_at, user_rating) VALUES
  ('u1', 'r2', '2026-03-22T22:15:00.000Z', 4.5),
  ('u1', 'r6', '2026-03-08T18:10:00.000Z', 4.3),
  ('u2', 'r4', '2026-04-02T21:30:00.000Z', 4.6),
  ('u3', 'r5', '2026-03-27T23:00:00.000Z', 4.4),
  ('u4', 'r7', '2026-04-01T20:05:00.000Z', 4.5),
  ('u4', 'r6', '2026-03-25T19:55:00.000Z', 4.7),
  ('u5', 'r8', '2026-03-31T15:30:00.000Z', 4.8);

INSERT INTO user_follows (follower_user_id, followed_user_id, created_at) VALUES
  ('u1', 'u2', '2026-03-10T12:00:00.000Z'),
  ('u1', 'u3', '2026-03-12T12:00:00.000Z'),
  ('u2', 'u5', '2026-03-14T12:00:00.000Z'),
  ('u3', 'u1', '2026-03-16T12:00:00.000Z'),
  ('u4', 'u2', '2026-03-18T12:00:00.000Z'),
  ('u5', 'u2', '2026-03-20T12:00:00.000Z'),
  ('u5', 'u4', '2026-03-22T12:00:00.000Z');

INSERT INTO feed_events (id, type, user_id, target_user_id, restaurant_id, review_id, created_at) VALUES
  ('feed1', 'review', 'u2', NULL, 'r4', 'rev6', '2026-04-02T21:30:00.000Z'),
  ('feed2', 'visited', 'u4', NULL, 'r7', NULL, '2026-04-01T20:05:00.000Z'),
  ('feed3', 'wishlist', 'u1', NULL, 'r8', NULL, '2026-04-03T09:20:00.000Z'),
  ('feed4', 'review', 'u5', NULL, 'r8', 'rev11', '2026-03-31T15:30:00.000Z'),
  ('feed5', 'review', 'u3', NULL, 'r5', 'rev7', '2026-03-27T23:00:00.000Z'),
  ('feed6', 'visited', 'u1', NULL, 'r2', NULL, '2026-03-22T22:15:00.000Z');

COMMIT;
